package comment

import (
	"context"
	"fmt"
	"os"
	"sort"
	"strconv"
	"strings"
	"testing"
	"time"

	"go.uber.org/zap"

	commentModel "meta-api/app/model/comment"
	appconfig "meta-api/config"
)

const (
	commentModerationReportCorpusPath         = "testdata/comment_moderation_comments.txt"
	commentModerationReportOutputPath         = "testdata/comment_moderation_report.txt"
	commentModerationExtraViolationCorpusPath = "testdata/comment_moderation_extra_violations.txt"
	commentModerationExtraViolationReportPath = "testdata/comment_moderation_extra_violations_report.txt"
	commentModerationNormalCorpusPath         = "testdata/comment_moderation_normal_comments.txt"
	commentModerationNormalReportPath         = "testdata/comment_moderation_normal_report.txt"
)

type commentModerationReportCase struct {
	Category   string
	UserID     uint64
	ArticleID  uint64
	ClientIP   string
	Content    string
	RawContent string
	Now        time.Time
}

type commentModerationReportRunner struct {
	service         *commentService
	userEvents      map[string][]time.Time
	ipEvents        map[string][]time.Time
	duplicateEvents map[string]int64
}

func TestCommentModerationReportCorpus(t *testing.T) {
	cases := loadCommentModerationReportCases(t, commentModerationReportCorpusPath)
	writeCommentModerationReport(t, cases, commentModerationReportOutputPath)
}

func TestCommentModerationExtraViolationCorpus(t *testing.T) {
	cases := loadCommentModerationReportCasesWithCategory(t, commentModerationExtraViolationCorpusPath, "violation_extra")
	writeCommentModerationReport(t, cases, commentModerationExtraViolationReportPath)
}

func TestCommentModerationNormalCorpus(t *testing.T) {
	cases := loadCommentModerationReportCasesWithCategory(t, commentModerationNormalCorpusPath, "normal")
	writeCommentModerationReport(t, cases, commentModerationNormalReportPath)
}

func writeCommentModerationReport(t *testing.T, cases []commentModerationReportCase, outputPath string) {
	t.Helper()
	runner := newCommentModerationReportRunner(t)
	statusCounts := make(map[string]int)
	reasonCounts := make(map[string]int)
	rows := make([]string, 0, len(cases))

	for index, item := range cases {
		result := runner.run(context.Background(), uint64(index+1), item)
		statusCounts[result.Status]++
		for _, reason := range result.Reasons {
			reasonCounts[reason]++
		}
		rows = append(rows, fmt.Sprintf(
			"%03d | status=%-8s | risk_score=%3d | final_score=%3d | deductions=%-120s | 原始评论=%s",
			index+1,
			result.Status,
			result.Score,
			moderationReportFinalScore(result.Score),
			formatModerationReportDeductions(result.Reasons),
			formatModerationReportContent(item.RawContent),
		))
	}

	reportLines := buildCommentModerationReportLines(cases, statusCounts, reasonCounts, rows)
	if err := os.WriteFile(outputPath, []byte(strings.Join(reportLines, "\n")+"\n"), 0644); err != nil {
		t.Fatalf("failed to write moderation report %s: %v", outputPath, err)
	}
}

func buildCommentModerationReportLines(cases []commentModerationReportCase, statusCounts map[string]int,
	reasonCounts map[string]int, rows []string) []string {
	lines := make([]string, 0, len(rows)+40)
	lines = append(lines,
		"# Comment moderation report",
		"# Generated by: go test ./app/service/comment -run TestCommentModerationReportCorpus -v",
		"",
		"## Scoring Basics",
		"审核引擎使用 risk_score（风险分）：从 0 开始，分数越高风险越高。",
		"报告里的 final_score 是便于查看的安全分：final_score = max(0, 100 - risk_score)。",
		fmt.Sprintf("决策阈值：risk_score < %d => approved；%d <= risk_score < %d => pending；risk_score >= %d => rejected。",
			defaultCommentModerationPendingScore,
			defaultCommentModerationPendingScore,
			defaultCommentModerationRejectScore,
			defaultCommentModerationRejectScore,
		),
		fmt.Sprintf("扣分项：关键词/AC=%d；正则=%d；编码链接=%d；涉政上下文=%d；安全上下文=%d；相似召回=%d；用户频率=%d；IP 频率=%d；重复内容=%d；重复内容强风险或硬拒=%d。",
			commentModerationKeywordScore,
			commentModerationRegexScore,
			commentModerationEncodedURLRiskScore,
			commentModerationPoliticalContextScore,
			commentModerationSafetyContextScore,
			defaultCommentModerationSimilarityScore,
			commentModerationUserRiskScore,
			commentModerationIPRiskScore,
			commentModerationDuplicateRiskScore,
			defaultCommentModerationRejectScore,
		),
		fmt.Sprintf("低质内容扣分：纯符号/空内容=%d；纯数字=%d；长重复字符=%d。",
			commentModerationTextQualityRiskScore,
			commentModerationTextQualityRiskScore,
			commentModerationTextQualityRiskScore,
		),
		"说明：同一类命中多个明细时只扣一次，例如命中多个关键词仍按关键词/AC 扣一次。",
		"",
		fmt.Sprintf("TOTAL cases=%d approved=%d pending=%d rejected=%d",
			len(cases),
			statusCounts[commentModel.StatusApproved],
			statusCounts[commentModel.StatusPending],
			statusCounts[commentModel.StatusRejected],
		),
	)
	lines = append(lines, "", "## Top Reasons")
	for _, reason := range topModerationReportReasons(reasonCounts, 20) {
		lines = append(lines, fmt.Sprintf("REASON %-64s count=%d", reason.name, reason.count))
	}
	lines = append(lines, "", "## Details")
	lines = append(lines, rows...)
	return lines
}

func newCommentModerationReportRunner(t testing.TB) *commentModerationReportRunner {
	t.Helper()
	return &commentModerationReportRunner{
		service: &commentService{
			config: &appconfig.Config{
				CommentModerationConfig: newTestCommentModerationConfig(t),
			},
			logger: zap.NewNop(),
		},
		userEvents:      make(map[string][]time.Time),
		ipEvents:        make(map[string][]time.Time),
		duplicateEvents: make(map[string]int64),
	}
}

func (r *commentModerationReportRunner) run(ctx context.Context, commentID uint64,
	item commentModerationReportCase) commentModerationResult {
	input := commentModerationInput{
		CommentID: commentID,
		UserID:    item.UserID,
		ArticleID: item.ArticleID,
		ClientIP:  item.ClientIP,
		Content:   item.Content,
		Now:       item.Now,
	}
	result := r.service.moderateCommentWithBehavior(ctx, input,
		func(_ context.Context, input commentModerationInput, view commentModerationTextView,
			cfg appconfig.CommentModerationConfig) []commentModerationSignal {
			keys := buildCommentModerationBehaviorKeys(input.UserID, input.ArticleID, input.ClientIP, view.Normalized)
			state := commentModerationBehaviorState{
				UserCount:      int64(len(recentModerationReportEvents(r.userEvents[keys.user], input.Now, commentModerationSecondsToDuration(cfg.Behavior.UserWindowSeconds)))),
				IPCount:        int64(len(recentModerationReportEvents(r.ipEvents[keys.ip], input.Now, commentModerationSecondsToDuration(cfg.Behavior.IPWindowSeconds)))),
				DuplicateCount: r.duplicateEvents[keys.duplicate],
			}
			return []commentModerationSignal{commentModerationBehaviorSignal(state, cfg)}
		},
	)
	r.record(input)
	return result
}

func (r *commentModerationReportRunner) record(input commentModerationInput) {
	normalized := normalizeCommentModerationText(input.Content)
	keys := buildCommentModerationBehaviorKeys(input.UserID, input.ArticleID, input.ClientIP, normalized)
	r.userEvents[keys.user] = append(r.userEvents[keys.user], input.Now)
	r.ipEvents[keys.ip] = append(r.ipEvents[keys.ip], input.Now)
	r.duplicateEvents[keys.duplicate]++
}

func loadCommentModerationReportCases(t *testing.T, path string) []commentModerationReportCase {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("failed to read moderation report corpus %s: %v", path, err)
	}

	baseTime := time.Unix(1700000000, 0)
	cases := make([]commentModerationReportCase, 0, 300)
	categoryCounts := make(map[string]int)
	corpus := strings.TrimSuffix(string(data), "\n")
	corpus = strings.TrimSuffix(corpus, "\r")
	for _, line := range strings.Split(corpus, "\n") {
		line = strings.TrimRight(line, "\r")
		category := commentModerationReportCategoryByIndex(len(cases))
		categoryIndex := categoryCounts[category]
		categoryCounts[category]++
		item := newCommentModerationReportCase(
			baseTime,
			len(cases),
			categoryIndex,
			category,
			stripModerationReportCaseLabel(line),
		)
		item.RawContent = line
		cases = append(cases, item)
	}

	return cases
}

func loadCommentModerationReportCasesWithCategory(t *testing.T, path, category string) []commentModerationReportCase {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("failed to read moderation report corpus %s: %v", path, err)
	}

	baseTime := time.Unix(1700000000, 0)
	corpus := strings.TrimSuffix(string(data), "\n")
	corpus = strings.TrimSuffix(corpus, "\r")
	if strings.TrimSpace(corpus) == "" {
		return nil
	}
	lines := strings.Split(corpus, "\n")
	cases := make([]commentModerationReportCase, 0, len(lines))
	for _, line := range lines {
		line = strings.TrimRight(line, "\r")
		item := newCommentModerationReportCase(
			baseTime,
			len(cases),
			len(cases),
			category,
			stripModerationReportCaseLabel(line),
		)
		item.RawContent = line
		cases = append(cases, item)
	}
	return cases
}

func stripModerationReportCaseLabel(value string) string {
	index := strings.Index(value, "：")
	if index < 0 || !strings.Contains(value[:index], "样例") {
		return value
	}
	return value[index+len("："):]
}

func commentModerationReportCategoryByIndex(index int) string {
	switch {
	case index < 50:
		return "normal"
	case index < 80:
		return "normalization_obfuscation"
	case index < 115:
		return "keyword"
	case index < 155:
		return "regex_url_phone"
	case index < 180:
		return "hard_rule_reject"
	case index < 210:
		return "similarity_recall"
	case index < 240:
		return "duplicate_content"
	case index < 260:
		return "user_frequency"
	case index < 280:
		return "ip_frequency"
	default:
		return "boundary"
	}
}

func newCommentModerationReportCase(baseTime time.Time, globalIndex, categoryIndex int, category, content string) commentModerationReportCase {
	item := commentModerationReportCase{
		Category: category,
		Content:  content,
		Now:      baseTime.Add(time.Duration(globalIndex) * time.Second),
	}
	switch category {
	case "normal":
		item.UserID = 100000 + uint64(categoryIndex)
		item.ArticleID = 200001
		item.ClientIP = fmt.Sprintf("10.0.%d.%d", categoryIndex/250, categoryIndex%250+1)
	case "normalization_obfuscation":
		item.UserID = 110000 + uint64(categoryIndex)
		item.ArticleID = 200002
		item.ClientIP = fmt.Sprintf("10.1.0.%d", categoryIndex+1)
	case "keyword":
		item.UserID = 120000 + uint64(categoryIndex)
		item.ArticleID = 200003
		item.ClientIP = fmt.Sprintf("10.2.0.%d", categoryIndex+1)
	case "regex_url_phone":
		item.UserID = 130000 + uint64(categoryIndex)
		item.ArticleID = 200004
		item.ClientIP = fmt.Sprintf("10.3.0.%d", categoryIndex+1)
	case "hard_rule_reject":
		item.UserID = 140000 + uint64(categoryIndex)
		item.ArticleID = 200005
		item.ClientIP = fmt.Sprintf("10.4.0.%d", categoryIndex+1)
	case "similarity_recall":
		item.UserID = 150000 + uint64(categoryIndex)
		item.ArticleID = 200006
		item.ClientIP = fmt.Sprintf("10.5.0.%d", categoryIndex+1)
	case "duplicate_content":
		group := categoryIndex / 5
		item.UserID = 160000 + uint64(group)
		item.ArticleID = 200007
		item.ClientIP = fmt.Sprintf("10.6.%d.%d", group, categoryIndex%5+1)
	case "user_frequency":
		item.UserID = 170001
		item.ArticleID = 200008
		item.ClientIP = fmt.Sprintf("10.7.0.%d", categoryIndex+1)
	case "ip_frequency":
		item.UserID = 180000 + uint64(categoryIndex)
		item.ArticleID = 200009
		item.ClientIP = "10.8.0.1"
	case "boundary":
		item.UserID = 190000 + uint64(categoryIndex)
		item.ArticleID = 200010
		item.ClientIP = fmt.Sprintf("10.9.0.%d", categoryIndex+1)
	default:
		item.UserID = 990000 + uint64(globalIndex)
		item.ArticleID = 299999
		item.ClientIP = fmt.Sprintf("10.99.%d.%d", globalIndex/250, globalIndex%250+1)
	}
	return item
}

func decodeModerationReportEscapes(value string) (string, error) {
	var builder strings.Builder
	builder.Grow(len(value))
	for i := 0; i < len(value); i++ {
		if value[i] != '\\' {
			builder.WriteByte(value[i])
			continue
		}
		if i+1 >= len(value) {
			builder.WriteByte(value[i])
			continue
		}
		i++
		switch value[i] {
		case '\\':
			builder.WriteByte('\\')
		case 'n':
			builder.WriteByte('\n')
		case 'r':
			builder.WriteByte('\r')
		case 't':
			builder.WriteByte('\t')
		case 'u':
			if i+4 >= len(value) {
				return "", fmt.Errorf("incomplete unicode escape")
			}
			code, err := strconv.ParseInt(value[i+1:i+5], 16, 32)
			if err != nil {
				return "", fmt.Errorf("invalid unicode escape \\u%s", value[i+1:i+5])
			}
			builder.WriteRune(rune(code))
			i += 4
		default:
			builder.WriteByte('\\')
			builder.WriteByte(value[i])
		}
	}
	return builder.String(), nil
}

func recentModerationReportEvents(values []time.Time, now time.Time, window time.Duration) []time.Time {
	start := now.Add(-window)
	recent := values[:0]
	for _, value := range values {
		if !value.Before(start) {
			recent = append(recent, value)
		}
	}
	return recent
}

func sortedModerationReportKeys(values map[string]map[string]int) []string {
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}

type moderationReportReasonCount struct {
	name  string
	count int
}

func topModerationReportReasons(values map[string]int, limit int) []moderationReportReasonCount {
	rows := make([]moderationReportReasonCount, 0, len(values))
	for name, count := range values {
		rows = append(rows, moderationReportReasonCount{name: name, count: count})
	}
	sort.Slice(rows, func(i, j int) bool {
		if rows[i].count == rows[j].count {
			return rows[i].name < rows[j].name
		}
		return rows[i].count > rows[j].count
	})
	if len(rows) > limit {
		return rows[:limit]
	}
	return rows
}

func moderationReportFinalScore(riskScore int) int {
	score := 100 - riskScore
	if score < 0 {
		return 0
	}
	return score
}

func formatModerationReportContent(value string) string {
	if value == "" {
		return strconv.Quote(value)
	}
	return strings.NewReplacer(
		"\n", `\n`,
		"\r", `\r`,
		"\t", `\t`,
	).Replace(value)
}

func formatModerationReportDeductions(reasons []string) string {
	if len(reasons) == 0 {
		return "none"
	}

	groups := map[string][]string{}
	for _, reason := range reasons {
		switch {
		case strings.HasPrefix(reason, "lexicon:"):
			groups["敏感词库"] = append(groups["敏感词库"], reason)
		case strings.HasPrefix(reason, "structure:"):
			groups["结构规则"] = append(groups["结构规则"], reason)
		case strings.HasPrefix(reason, "context:"):
			groups["上下文规则"] = append(groups["上下文规则"], reason)
		case strings.HasPrefix(reason, "behavior:"):
			groups["行为风险"] = append(groups["行为风险"], reason)
		case strings.HasPrefix(reason, "reject_keyword:"):
			groups["硬规则关键词"] = append(groups["硬规则关键词"], strings.TrimPrefix(reason, "reject_keyword:"))
		case strings.HasPrefix(reason, "reject_keyword_variant:"):
			groups["硬规则近形/谐音"] = append(groups["硬规则近形/谐音"], strings.TrimPrefix(reason, "reject_keyword_variant:"))
		case strings.HasPrefix(reason, "reject_abuse_keyword:"):
			groups["英文辱骂"] = append(groups["英文辱骂"], strings.TrimPrefix(reason, "reject_abuse_keyword:"))
		case strings.HasPrefix(reason, "reject_abuse_variant:"):
			groups["英文辱骂"] = append(groups["英文辱骂"], strings.TrimPrefix(reason, "reject_abuse_variant:"))
		case strings.HasPrefix(reason, "reject_regex:"):
			groups["硬规则正则"] = append(groups["硬规则正则"], strings.TrimPrefix(reason, "reject_regex:"))
		case strings.HasPrefix(reason, "reject_patch_rule:"):
			groups["补洞规则拒绝"] = append(groups["补洞规则拒绝"], strings.TrimPrefix(reason, "reject_patch_rule:"))
		case strings.HasPrefix(reason, "pending_keyword:"):
			groups["关键词/AC"] = append(groups["关键词/AC"], strings.TrimPrefix(reason, "pending_keyword:"))
		case strings.HasPrefix(reason, "pending_regex:"):
			groups["正则"] = append(groups["正则"], strings.TrimPrefix(reason, "pending_regex:"))
		case strings.HasPrefix(reason, "pending_patch_rule:"):
			groups["补洞规则待审"] = append(groups["补洞规则待审"], strings.TrimPrefix(reason, "pending_patch_rule:"))
		case strings.HasPrefix(reason, "pending_contact_shape:"):
			groups["联系方式形态"] = append(groups["联系方式形态"], strings.TrimPrefix(reason, "pending_contact_shape:"))
		case strings.HasPrefix(reason, "pending_encoded_url:"):
			groups["编码链接"] = append(groups["编码链接"], strings.TrimPrefix(reason, "pending_encoded_url:"))
		case strings.HasPrefix(reason, "pending_political_context:"):
			groups["涉政上下文"] = append(groups["涉政上下文"], strings.TrimPrefix(reason, "pending_political_context:"))
		case strings.HasPrefix(reason, "pending_safety_context:"):
			groups["安全上下文"] = append(groups["安全上下文"], strings.TrimPrefix(reason, "pending_safety_context:"))
		case strings.HasPrefix(reason, "similarity:"):
			groups["相似召回"] = append(groups["相似召回"], strings.TrimPrefix(reason, "similarity:"))
		case reason == "behavior_user_frequency":
			groups["用户频率"] = append(groups["用户频率"], "窗口内用户提交次数达到阈值")
		case reason == "behavior_ip_frequency":
			groups["IP频率"] = append(groups["IP频率"], "窗口内 IP 提交次数达到阈值")
		case reason == "behavior_duplicate":
			groups["重复内容"] = append(groups["重复内容"], "重复次数达到待审核阈值")
		case reason == "behavior_duplicate_reject":
			groups["重复内容强风险"] = append(groups["重复内容强风险"], "重复次数达到拒绝阈值")
		case reason == "text_quality_no_words":
			groups["低质内容"] = append(groups["低质内容"], "空内容或纯符号")
		case reason == "text_quality_numeric":
			groups["低质内容"] = append(groups["低质内容"], "纯数字")
		case reason == "text_quality_repeated":
			groups["低质内容"] = append(groups["低质内容"], "长重复字符")
		default:
			groups["其他"] = append(groups["其他"], reason)
		}
	}

	order := []string{
		"敏感词库",
		"结构规则",
		"上下文规则",
		"行为风险",
		"硬规则关键词",
		"硬规则近形/谐音",
		"英文辱骂",
		"硬规则正则",
		"补洞规则拒绝",
		"补洞规则待审",
		"关键词/AC",
		"正则",
		"联系方式形态",
		"编码链接",
		"涉政上下文",
		"安全上下文",
		"相似召回",
		"用户频率",
		"IP频率",
		"重复内容",
		"重复内容强风险",
		"低质内容",
		"其他",
	}
	parts := make([]string, 0, len(groups))
	for _, name := range order {
		values := groups[name]
		if len(values) == 0 {
			continue
		}
		parts = append(parts, fmt.Sprintf("扣%d:%s[%s]", moderationReportDeductionScore(name), name, strings.Join(values, ",")))
	}
	return strings.Join(parts, "; ")
}

func moderationReportDeductionScore(name string) int {
	switch name {
	case "敏感词库", "结构规则", "上下文规则", "行为风险":
		return defaultCommentModerationPendingScore
	case "硬规则关键词", "硬规则近形/谐音", "英文辱骂", "硬规则正则", "补洞规则拒绝", "重复内容强风险":
		return defaultCommentModerationRejectScore
	case "关键词/AC", "补洞规则待审":
		return commentModerationKeywordScore
	case "正则", "联系方式形态":
		return commentModerationRegexScore
	case "编码链接":
		return commentModerationEncodedURLRiskScore
	case "涉政上下文":
		return commentModerationPoliticalContextScore
	case "安全上下文":
		return commentModerationSafetyContextScore
	case "相似召回":
		return defaultCommentModerationSimilarityScore
	case "用户频率":
		return commentModerationUserRiskScore
	case "IP频率":
		return commentModerationIPRiskScore
	case "重复内容":
		return commentModerationDuplicateRiskScore
	case "低质内容":
		return commentModerationTextQualityRiskScore
	default:
		return 0
	}
}
