log:
  mysql_full_log: "./log/mysql.full.log"
  mysql_slow_log: "./log/mysql.slow.log"
  http_info_log: "./log/http.info.log"
  http_warn_log: "./log/http.warn.log"
  http_err_log: "./log/http.err.log"
  max_size: 1
  max_age: 180
  max_backups: 30
  compress: false

retry:
  max_retries: 3
  initial_delay: 1s
  max_delay: 60s
  jitter_factor: 0.3

mysql:
  max_open_conn: 40
  max_idle_conn: 10
  conn_max_lifetime: 30m
  conn_max_idle_time: 5m
  log_full_sql: false
  slow_threshold: 100ms

redis:
  db: 0

oauth:
  github:
    client_id: ""
    redirect_uri: ""
  google:
    client_id: ""
    redirect_uri: ""

admin_info:
  issuer: BingBingStudentBlogWebsite
  account_name: 1425723960@qq.com

bug_feedback:
  smtp:
    host: smtp.qq.com
    port: 465
    username: "liubing.xyz@qq.com"
    from: ""
    from_name: JSON Tool Feedback
